In [ ]:
# prompt: import pandas , matplotlib , sklearn

import pandas as pd
import matplotlib.pyplot as plt
import sklearn


In [1]:
# prompt: import/content/Aarti Aarti - revolutioncart_data.xlsx

import pandas as pd
df = pd.read_excel('/content/Aarti Aarti - revolutioncart_data.xlsx')


In [2]:
# prompt: df

print(df)


    month_of_year  is_holiday_season  total_sku_count  average_product_rating  \
0               1                  0      12440.14782                3.852202   
1               2                  0      12287.09708                3.913549   
2               3                  0      13554.97763                4.196981   
3               4                  0      14912.24666                4.079651   
4               5                  0      13636.99114                3.907948   
..            ...                ...              ...                     ...   
79              8                  0      48028.15391                3.849764   
80              9                  0      50277.97865                4.206576   
81             10                  0      51336.69082                4.096457   
82             11                  1      52939.40000                4.178313   
83             12                  1      51425.16345                4.393259   

    new_product_releases  t

In [5]:
# prompt: consider monthly_revenue as y and other as X

X = df.drop('monthly_revenue', axis=1)
y = df['monthly_revenue']


In [7]:
# prompt: split the data  into train  and test

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


In [8]:
# prompt:  check score with X_test and y_test

from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(X_train, y_train)

score = model.score(X_test, y_test)
print(f"R-squared score on test data: {score}")


R-squared score on test data: 0.9843806772238421


In [22]:
# prompt: do lasso regression

from sklearn.linear_model import Lasso

# Create a Lasso regression model
lasso_model = Lasso(alpha=0.1)  # You can adjust the alpha value

# Fit the model to the training data
lasso_model.fit(X_train, y_train)

# Evaluate the model on the test data
lasso_score = lasso_model.score(X_test, y_test)
print(f"R-squared score for Lasso regression on test data: {lasso_score}")


R-squared score for Lasso regression on test data: 0.9843754499822968


/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_coordinate_descent.py:697: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.467e+08, tolerance: 5.508e+06
  model = cd_fast.enet_coordinate_descent(


In [9]:
# prompt:  do cross val for knn model

from sklearn.neighbors import KNeighborsRegressor
from sklearn.model_selection import cross_val_score

# Assuming X and y are your features and target variable

knn_model = KNeighborsRegressor()  # You can adjust the n_neighbors parameter

cv_scores = cross_val_score(knn_model, X, y, cv=5)  # Use 5-fold cross-validation

print("Cross-validation scores:", cv_scores)
print("Average cross-validation score:", cv_scores.mean())


Cross-validation scores: [-1.03505599 -0.61730256 -0.00982261 -0.54937713 -0.88492278]
Average cross-validation score: -0.6192962141352556


In [10]:
# prompt: make knn model for X_train and y_train

knn_model = KNeighborsRegressor()
knn_model.fit(X_train, y_train)



KNeighborsRegressor()

In [11]:
# prompt:  do cross val for knn model

from sklearn.model_selection import cross_val_score

knn_model = KNeighborsRegressor()
cv_scores = cross_val_score(knn_model, X, y, cv=5)  # Use 5-fold cross-validation

print("Cross-validation scores:", cv_scores)
print("Average cross-validation score:", cv_scores.mean())


Cross-validation scores: [-1.03505599 -0.61730256 -0.00982261 -0.54937713 -0.88492278]
Average cross-validation score: -0.6192962141352556


In [12]:
# prompt: k value identify with  gridsearch

from sklearn.model_selection import GridSearchCV

# Define the parameter grid for k
param_grid = {'n_neighbors': [1, 3, 5, 7, 9, 11]}

# Create a KNeighborsRegressor object
knn_model = KNeighborsRegressor()

# Create a GridSearchCV object
grid_search = GridSearchCV(knn_model, param_grid, cv=5)

# Fit the GridSearchCV object to the data
grid_search.fit(X_train, y_train)

# Print the best parameters and the best score
print("Best parameters:", grid_search.best_params_)
print("Best cross-validation score:", grid_search.best_score_)

# You can access the best model directly using grid_search.best_estimator_
best_knn_model = grid_search.best_estimator_


Best parameters: {'n_neighbors': 5}
Best cross-validation score: 0.05280550335512826


/usr/local/lib/python3.10/dist-packages/numpy/ma/core.py:2820: RuntimeWarning: invalid value encountered in cast
  _data = np.array(data, dtype=dtype, copy=copy,


In [15]:
# prompt: do cross val for  dt_score

from sklearn.tree import DecisionTreeRegressor
from sklearn.model_selection import cross_val_score

dt_model = DecisionTreeRegressor()

dt_cv_scores = cross_val_score(dt_model, X, y, cv=5)

print("Cross-validation scores for Decision Tree:", dt_cv_scores)
print("Average cross-validation score for Decision Tree:", dt_cv_scores.mean())


Cross-validation scores for Decision Tree: [-1.15149167  0.21767129 -0.32027899 -0.2029037   0.07851669]
Average cross-validation score for Decision Tree: -0.27569727566220453


In [ ]:
# prompt: show decision tree diagram with gini index

import matplotlib.pyplot as plt
from sklearn.tree import plot_tree

# Train the decision tree model on the training data
dt_model.fit(X_train, y_train)

# Plot the decision tree
plt.figure(figsize=(20, 10))
plot_tree(dt_model, feature_names=X.columns, filled=True, rounded=True, class_names=['monthly_revenue'])
plt.show()


In [16]:
# prompt: make a random forest model on X_train and y_train

from sklearn.ensemble import RandomForestRegressor

# Create a Random Forest model
rf_model = RandomForestRegressor(random_state=42)

# Train the model on the training data
rf_model.fit(X_train, y_train)

# You can then evaluate the model's performance on the test data or using cross-validation


RandomForestRegressor(random_state=42)

In [17]:
# prompt: check score of rf model

rf_score = rf_model.score(X_test, y_test)
print(f"R-squared score for Random Forest model on test data: {rf_score}")


R-squared score for Random Forest model on test data: 0.5493956300773817


In [18]:
# prompt:  make confusion matrix for rf model

from sklearn.metrics import confusion_matrix
import numpy as np

# Get predictions on the test set
y_pred = rf_model.predict(X_test)

# Convert predicted values to class labels (if applicable)
# For regression, you might need to round or threshold the predictions
# For example: y_pred_classes = np.round(y_pred)

# Convert true values to class labels (if applicable)

# Calculate the confusion matrix
# cm = confusion_matrix(y_test, y_pred_classes)


# If you are working with regression, you might want to discretize the predictions and targets into bins or categories
# before creating the confusion matrix. You can choose the number of bins based on the range of the target variable.

bins = 10  # You can adjust this to create more or fewer bins
y_pred_binned = np.digitize(y_pred, bins=np.linspace(y.min(), y.max(), bins))
y_test_binned = np.digitize(y_test, bins=np.linspace(y.min(), y.max(), bins))

cm = confusion_matrix(y_test_binned, y_pred_binned)

print("Confusion Matrix:")
print(cm)


Confusion Matrix:
[[0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 2 0 2 0 0]
 [0 0 1 1 2 0 0]
 [0 0 0 0 1 1 0]
 [0 0 0 1 1 2 0]
 [0 0 0 0 1 0 1]]


In [20]:
# prompt: make SVM model

from sklearn.svm import SVR

# Create an SVM model
svm_model = SVR()

# Train the model
svm_model.fit(X_train, y_train)

# Evaluate the model
svm_score = svm_model.score(X_test, y_test)
print(f"R-squared score for SVM model on test data: {svm_score}")

# You can further explore hyperparameter tuning for the SVM model using GridSearchCV
# for better performance.


R-squared score for SVM model on test data: -0.026658349674526738


In [21]:
# prompt: make ensemble model by considering SVM,kNN,Dt

from sklearn.ensemble import VotingRegressor

# Assuming you have already trained and tuned your individual models:
# best_knn_model, dt_model, svm_model

# Create a voting regressor ensemble
ensemble_model = VotingRegressor(estimators=[
    ('knn', best_knn_model),
    ('dt', dt_model),
    ('svm', svm_model)
])

# Train the ensemble model on the training data
ensemble_model.fit(X_train, y_train)

# Evaluate the ensemble model on the test data
ensemble_score = ensemble_model.score(X_test, y_test)
print(f"R-squared score for Ensemble model on test data: {ensemble_score}")


R-squared score for Ensemble model on test data: 0.4686087236685207


In [23]:
# prompt:  do cross val voting clf

from sklearn.model_selection import cross_val_score

# Assuming you have already created your individual models and ensemble_model
# best_knn_model, dt_model, svm_model, ensemble_model

# Perform cross-validation on the ensemble model
cv_scores_ensemble = cross_val_score(ensemble_model, X, y, cv=5)

print("Cross-validation scores for Ensemble model:", cv_scores_ensemble)
print("Average cross-validation score for Ensemble model:", cv_scores_ensemble.mean())


Cross-validation scores for Ensemble model: [-0.80534512  0.13056564  0.05503607  0.07503336 -0.31362503]
Average cross-validation score for Ensemble model: -0.17166701709927365


In [27]:
# prompt: make boosting model for X_train and y_train

from sklearn.ensemble import GradientBoostingRegressor

# Create a Gradient Boosting model
gb_model = GradientBoostingRegressor(random_state=42)

# Train the model on the training data
gb_model.fit(X_train, y_train)

# Evaluate the model on the test data
gb_score = gb_model.score(X_test, y_test)
print(f"R-squared score for Gradient Boosting model on test data: {gb_score}")


R-squared score for Gradient Boosting model on test data: 0.6045751918217221
